version: "2.2"
services:
  sqlserver:
    image: metaskills/mssql-server-linux-rails
  ci:
    environment:
      - ACTIVERECORD_UNITTEST_HOST=sqlserver
    build:
      context: .
      dockerfile: Dockerfile.ci
    command: test/bin/wait-for.sh sqlserver:1433 -- bundle exec rake test
    depends_on:
      - "sqlserver"
